on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        schema: [moran, moran_aux, moran.hint, moran.charset]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Set up Mira
        run: |
          wget https://github.com/rimeinn/mira/releases/download/latest/mira
          chmod +x mira
      - name: Build
        run: cd tools && sudo apt-get install -y opencc && uv run make quick
      - name: Test ${{ matrix.schema }}
        run: ./mira -C cache tests/${{ matrix.schema }}.test.yaml

  dict_qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Check if the simplified table contains traditional words by mistake
        run: cd tools && uv run check_simp_table.py
